// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package uc

import (
	"context"
	"time"

	"github.com/google/go-github/v73/github"
	mock "github.com/stretchr/testify/mock"
)

// NewMockCreateBackupUseCase creates a new instance of MockCreateBackupUseCase. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockCreateBackupUseCase(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockCreateBackupUseCase {
	mock := &MockCreateBackupUseCase{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockCreateBackupUseCase is an autogenerated mock type for the CreateBackupUseCase type
type MockCreateBackupUseCase struct {
	mock.Mock
}

type MockCreateBackupUseCase_Expecter struct {
	mock *mock.Mock
}

func (_m *MockCreateBackupUseCase) EXPECT() *MockCreateBackupUseCase_Expecter {
	return &MockCreateBackupUseCase_Expecter{mock: &_m.Mock}
}

// Do provides a mock function for the type MockCreateBackupUseCase
func (_mock *MockCreateBackupUseCase) Do(ctx context.Context, organization string, saveBackupFunc SaveBackupFunc) (string, error) {
	ret := _mock.Called(ctx, organization, saveBackupFunc)

	if len(ret) == 0 {
		panic("no return value specified for Do")
	}

	var r0 string
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, SaveBackupFunc) (string, error)); ok {
		return returnFunc(ctx, organization, saveBackupFunc)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, SaveBackupFunc) string); ok {
		r0 = returnFunc(ctx, organization, saveBackupFunc)
	} else {
		r0 = ret.Get(0).(string)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, SaveBackupFunc) error); ok {
		r1 = returnFunc(ctx, organization, saveBackupFunc)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockCreateBackupUseCase_Do_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Do'
type MockCreateBackupUseCase_Do_Call struct {
	*mock.Call
}

// Do is a helper method to define mock.On call
//   - ctx context.Context
//   - organization string
//   - saveBackupFunc SaveBackupFunc
func (_e *MockCreateBackupUseCase_Expecter) Do(ctx interface{}, organization interface{}, saveBackupFunc interface{}) *MockCreateBackupUseCase_Do_Call {
	return &MockCreateBackupUseCase_Do_Call{Call: _e.mock.On("Do", ctx, organization, saveBackupFunc)}
}

func (_c *MockCreateBackupUseCase_Do_Call) Run(run func(ctx context.Context, organization string, saveBackupFunc SaveBackupFunc)) *MockCreateBackupUseCase_Do_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 SaveBackupFunc
		if args[2] != nil {
			arg2 = args[2].(SaveBackupFunc)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockCreateBackupUseCase_Do_Call) Return(s string, err error) *MockCreateBackupUseCase_Do_Call {
	_c.Call.Return(s, err)
	return _c
}

func (_c *MockCreateBackupUseCase_Do_Call) RunAndReturn(run func(ctx context.Context, organization string, saveBackupFunc SaveBackupFunc) (string, error)) *MockCreateBackupUseCase_Do_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockCreateLocalBackupUseCase creates a new instance of MockCreateLocalBackupUseCase. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockCreateLocalBackupUseCase(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockCreateLocalBackupUseCase {
	mock := &MockCreateLocalBackupUseCase{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockCreateLocalBackupUseCase is an autogenerated mock type for the CreateLocalBackupUseCase type
type MockCreateLocalBackupUseCase struct {
	mock.Mock
}

type MockCreateLocalBackupUseCase_Expecter struct {
	mock *mock.Mock
}

func (_m *MockCreateLocalBackupUseCase) EXPECT() *MockCreateLocalBackupUseCase_Expecter {
	return &MockCreateLocalBackupUseCase_Expecter{mock: &_m.Mock}
}

// Do provides a mock function for the type MockCreateLocalBackupUseCase
func (_mock *MockCreateLocalBackupUseCase) Do(ctx context.Context, organization string, backupPath string) (string, error) {
	ret := _mock.Called(ctx, organization, backupPath)

	if len(ret) == 0 {
		panic("no return value specified for Do")
	}

	var r0 string
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string) (string, error)); ok {
		return returnFunc(ctx, organization, backupPath)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string) string); ok {
		r0 = returnFunc(ctx, organization, backupPath)
	} else {
		r0 = ret.Get(0).(string)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, string) error); ok {
		r1 = returnFunc(ctx, organization, backupPath)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockCreateLocalBackupUseCase_Do_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Do'
type MockCreateLocalBackupUseCase_Do_Call struct {
	*mock.Call
}

// Do is a helper method to define mock.On call
//   - ctx context.Context
//   - organization string
//   - backupPath string
func (_e *MockCreateLocalBackupUseCase_Expecter) Do(ctx interface{}, organization interface{}, backupPath interface{}) *MockCreateLocalBackupUseCase_Do_Call {
	return &MockCreateLocalBackupUseCase_Do_Call{Call: _e.mock.On("Do", ctx, organization, backupPath)}
}

func (_c *MockCreateLocalBackupUseCase_Do_Call) Run(run func(ctx context.Context, organization string, backupPath string)) *MockCreateLocalBackupUseCase_Do_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockCreateLocalBackupUseCase_Do_Call) Return(s string, err error) *MockCreateLocalBackupUseCase_Do_Call {
	_c.Call.Return(s, err)
	return _c
}

func (_c *MockCreateLocalBackupUseCase_Do_Call) RunAndReturn(run func(ctx context.Context, organization string, backupPath string) (string, error)) *MockCreateLocalBackupUseCase_Do_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockCreateRemoteBackupUseCase creates a new instance of MockCreateRemoteBackupUseCase. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockCreateRemoteBackupUseCase(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockCreateRemoteBackupUseCase {
	mock := &MockCreateRemoteBackupUseCase{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockCreateRemoteBackupUseCase is an autogenerated mock type for the CreateRemoteBackupUseCase type
type MockCreateRemoteBackupUseCase struct {
	mock.Mock
}

type MockCreateRemoteBackupUseCase_Expecter struct {
	mock *mock.Mock
}

func (_m *MockCreateRemoteBackupUseCase) EXPECT() *MockCreateRemoteBackupUseCase_Expecter {
	return &MockCreateRemoteBackupUseCase_Expecter{mock: &_m.Mock}
}

// Do provides a mock function for the type MockCreateRemoteBackupUseCase
func (_mock *MockCreateRemoteBackupUseCase) Do(ctx context.Context, organization string) (string, error) {
	ret := _mock.Called(ctx, organization)

	if len(ret) == 0 {
		panic("no return value specified for Do")
	}

	var r0 string
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (string, error)); ok {
		return returnFunc(ctx, organization)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) string); ok {
		r0 = returnFunc(ctx, organization)
	} else {
		r0 = ret.Get(0).(string)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, organization)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockCreateRemoteBackupUseCase_Do_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Do'
type MockCreateRemoteBackupUseCase_Do_Call struct {
	*mock.Call
}

// Do is a helper method to define mock.On call
//   - ctx context.Context
//   - organization string
func (_e *MockCreateRemoteBackupUseCase_Expecter) Do(ctx interface{}, organization interface{}) *MockCreateRemoteBackupUseCase_Do_Call {
	return &MockCreateRemoteBackupUseCase_Do_Call{Call: _e.mock.On("Do", ctx, organization)}
}

func (_c *MockCreateRemoteBackupUseCase_Do_Call) Run(run func(ctx context.Context, organization string)) *MockCreateRemoteBackupUseCase_Do_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockCreateRemoteBackupUseCase_Do_Call) Return(s string, err error) *MockCreateRemoteBackupUseCase_Do_Call {
	_c.Call.Return(s, err)
	return _c
}

func (_c *MockCreateRemoteBackupUseCase_Do_Call) RunAndReturn(run func(ctx context.Context, organization string) (string, error)) *MockCreateRemoteBackupUseCase_Do_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockGetOrganizationArchiveUrlUseCase creates a new instance of MockGetOrganizationArchiveUrlUseCase. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockGetOrganizationArchiveUrlUseCase(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockGetOrganizationArchiveUrlUseCase {
	mock := &MockGetOrganizationArchiveUrlUseCase{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockGetOrganizationArchiveUrlUseCase is an autogenerated mock type for the GetOrganizationArchiveUrlUseCase type
type MockGetOrganizationArchiveUrlUseCase struct {
	mock.Mock
}

type MockGetOrganizationArchiveUrlUseCase_Expecter struct {
	mock *mock.Mock
}

func (_m *MockGetOrganizationArchiveUrlUseCase) EXPECT() *MockGetOrganizationArchiveUrlUseCase_Expecter {
	return &MockGetOrganizationArchiveUrlUseCase_Expecter{mock: &_m.Mock}
}

// Do provides a mock function for the type MockGetOrganizationArchiveUrlUseCase
func (_mock *MockGetOrganizationArchiveUrlUseCase) Do(ctx context.Context, organization string, organizationID int64) (string, error) {
	ret := _mock.Called(ctx, organization, organizationID)

	if len(ret) == 0 {
		panic("no return value specified for Do")
	}

	var r0 string
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, int64) (string, error)); ok {
		return returnFunc(ctx, organization, organizationID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, int64) string); ok {
		r0 = returnFunc(ctx, organization, organizationID)
	} else {
		r0 = ret.Get(0).(string)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, int64) error); ok {
		r1 = returnFunc(ctx, organization, organizationID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockGetOrganizationArchiveUrlUseCase_Do_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Do'
type MockGetOrganizationArchiveUrlUseCase_Do_Call struct {
	*mock.Call
}

// Do is a helper method to define mock.On call
//   - ctx context.Context
//   - organization string
//   - organizationID int64
func (_e *MockGetOrganizationArchiveUrlUseCase_Expecter) Do(ctx interface{}, organization interface{}, organizationID interface{}) *MockGetOrganizationArchiveUrlUseCase_Do_Call {
	return &MockGetOrganizationArchiveUrlUseCase_Do_Call{Call: _e.mock.On("Do", ctx, organization, organizationID)}
}

func (_c *MockGetOrganizationArchiveUrlUseCase_Do_Call) Run(run func(ctx context.Context, organization string, organizationID int64)) *MockGetOrganizationArchiveUrlUseCase_Do_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 int64
		if args[2] != nil {
			arg2 = args[2].(int64)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockGetOrganizationArchiveUrlUseCase_Do_Call) Return(s string, err error) *MockGetOrganizationArchiveUrlUseCase_Do_Call {
	_c.Call.Return(s, err)
	return _c
}

func (_c *MockGetOrganizationArchiveUrlUseCase_Do_Call) RunAndReturn(run func(ctx context.Context, organization string, organizationID int64) (string, error)) *MockGetOrganizationArchiveUrlUseCase_Do_Call {
	_c.Call.Return(run)
	return _c
}

// WithDurationOptions provides a mock function for the type MockGetOrganizationArchiveUrlUseCase
func (_mock *MockGetOrganizationArchiveUrlUseCase) WithDurationOptions(timeout time.Duration, ticker time.Duration) GetOrganizationArchiveUrlUseCase {
	ret := _mock.Called(timeout, ticker)

	if len(ret) == 0 {
		panic("no return value specified for WithDurationOptions")
	}

	var r0 GetOrganizationArchiveUrlUseCase
	if returnFunc, ok := ret.Get(0).(func(time.Duration, time.Duration) GetOrganizationArchiveUrlUseCase); ok {
		r0 = returnFunc(timeout, ticker)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(GetOrganizationArchiveUrlUseCase)
		}
	}
	return r0
}

// MockGetOrganizationArchiveUrlUseCase_WithDurationOptions_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'WithDurationOptions'
type MockGetOrganizationArchiveUrlUseCase_WithDurationOptions_Call struct {
	*mock.Call
}

// WithDurationOptions is a helper method to define mock.On call
//   - timeout time.Duration
//   - ticker time.Duration
func (_e *MockGetOrganizationArchiveUrlUseCase_Expecter) WithDurationOptions(timeout interface{}, ticker interface{}) *MockGetOrganizationArchiveUrlUseCase_WithDurationOptions_Call {
	return &MockGetOrganizationArchiveUrlUseCase_WithDurationOptions_Call{Call: _e.mock.On("WithDurationOptions", timeout, ticker)}
}

func (_c *MockGetOrganizationArchiveUrlUseCase_WithDurationOptions_Call) Run(run func(timeout time.Duration, ticker time.Duration)) *MockGetOrganizationArchiveUrlUseCase_WithDurationOptions_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 time.Duration
		if args[0] != nil {
			arg0 = args[0].(time.Duration)
		}
		var arg1 time.Duration
		if args[1] != nil {
			arg1 = args[1].(time.Duration)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockGetOrganizationArchiveUrlUseCase_WithDurationOptions_Call) Return(getOrganizationArchiveUrlUseCase GetOrganizationArchiveUrlUseCase) *MockGetOrganizationArchiveUrlUseCase_WithDurationOptions_Call {
	_c.Call.Return(getOrganizationArchiveUrlUseCase)
	return _c
}

func (_c *MockGetOrganizationArchiveUrlUseCase_WithDurationOptions_Call) RunAndReturn(run func(timeout time.Duration, ticker time.Duration) GetOrganizationArchiveUrlUseCase) *MockGetOrganizationArchiveUrlUseCase_WithDurationOptions_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockListPrivateReposUseCase creates a new instance of MockListPrivateReposUseCase. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockListPrivateReposUseCase(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockListPrivateReposUseCase {
	mock := &MockListPrivateReposUseCase{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockListPrivateReposUseCase is an autogenerated mock type for the ListPrivateReposUseCase type
type MockListPrivateReposUseCase struct {
	mock.Mock
}

type MockListPrivateReposUseCase_Expecter struct {
	mock *mock.Mock
}

func (_m *MockListPrivateReposUseCase) EXPECT() *MockListPrivateReposUseCase_Expecter {
	return &MockListPrivateReposUseCase_Expecter{mock: &_m.Mock}
}

// Do provides a mock function for the type MockListPrivateReposUseCase
func (_mock *MockListPrivateReposUseCase) Do(ctx context.Context, organization string) ([]github.Repository, error) {
	ret := _mock.Called(ctx, organization)

	if len(ret) == 0 {
		panic("no return value specified for Do")
	}

	var r0 []github.Repository
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) ([]github.Repository, error)); ok {
		return returnFunc(ctx, organization)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) []github.Repository); ok {
		r0 = returnFunc(ctx, organization)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]github.Repository)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, organization)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockListPrivateReposUseCase_Do_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Do'
type MockListPrivateReposUseCase_Do_Call struct {
	*mock.Call
}

// Do is a helper method to define mock.On call
//   - ctx context.Context
//   - organization string
func (_e *MockListPrivateReposUseCase_Expecter) Do(ctx interface{}, organization interface{}) *MockListPrivateReposUseCase_Do_Call {
	return &MockListPrivateReposUseCase_Do_Call{Call: _e.mock.On("Do", ctx, organization)}
}

func (_c *MockListPrivateReposUseCase_Do_Call) Run(run func(ctx context.Context, organization string)) *MockListPrivateReposUseCase_Do_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockListPrivateReposUseCase_Do_Call) Return(repositorys []github.Repository, err error) *MockListPrivateReposUseCase_Do_Call {
	_c.Call.Return(repositorys, err)
	return _c
}

func (_c *MockListPrivateReposUseCase_Do_Call) RunAndReturn(run func(ctx context.Context, organization string) ([]github.Repository, error)) *MockListPrivateReposUseCase_Do_Call {
	_c.Call.Return(run)
	return _c
}
