// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package github

import (
	"context"

	"github.com/google/go-github/v74/github"
	mock "github.com/stretchr/testify/mock"
)

// NewMockClient creates a new instance of MockClient. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockClient(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockClient {
	mock := &MockClient{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockClient is an autogenerated mock type for the Client type
type MockClient struct {
	mock.Mock
}

type MockClient_Expecter struct {
	mock *mock.Mock
}

func (_m *MockClient) EXPECT() *MockClient_Expecter {
	return &MockClient_Expecter{mock: &_m.Mock}
}

// GetMigrationArchiveURL provides a mock function for the type MockClient
func (_mock *MockClient) GetMigrationArchiveURL(ctx context.Context, organization string, organizationID int64) (string, error) {
	ret := _mock.Called(ctx, organization, organizationID)

	if len(ret) == 0 {
		panic("no return value specified for GetMigrationArchiveURL")
	}

	var r0 string
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, int64) (string, error)); ok {
		return returnFunc(ctx, organization, organizationID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, int64) string); ok {
		r0 = returnFunc(ctx, organization, organizationID)
	} else {
		r0 = ret.Get(0).(string)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, int64) error); ok {
		r1 = returnFunc(ctx, organization, organizationID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockClient_GetMigrationArchiveURL_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetMigrationArchiveURL'
type MockClient_GetMigrationArchiveURL_Call struct {
	*mock.Call
}

// GetMigrationArchiveURL is a helper method to define mock.On call
//   - ctx context.Context
//   - organization string
//   - organizationID int64
func (_e *MockClient_Expecter) GetMigrationArchiveURL(ctx interface{}, organization interface{}, organizationID interface{}) *MockClient_GetMigrationArchiveURL_Call {
	return &MockClient_GetMigrationArchiveURL_Call{Call: _e.mock.On("GetMigrationArchiveURL", ctx, organization, organizationID)}
}

func (_c *MockClient_GetMigrationArchiveURL_Call) Run(run func(ctx context.Context, organization string, organizationID int64)) *MockClient_GetMigrationArchiveURL_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 int64
		if args[2] != nil {
			arg2 = args[2].(int64)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockClient_GetMigrationArchiveURL_Call) Return(s string, err error) *MockClient_GetMigrationArchiveURL_Call {
	_c.Call.Return(s, err)
	return _c
}

func (_c *MockClient_GetMigrationArchiveURL_Call) RunAndReturn(run func(ctx context.Context, organization string, organizationID int64) (string, error)) *MockClient_GetMigrationArchiveURL_Call {
	_c.Call.Return(run)
	return _c
}

// GetMigrationStatus provides a mock function for the type MockClient
func (_mock *MockClient) GetMigrationStatus(ctx context.Context, organization string, migrationID int64) (*github.Migration, error) {
	ret := _mock.Called(ctx, organization, migrationID)

	if len(ret) == 0 {
		panic("no return value specified for GetMigrationStatus")
	}

	var r0 *github.Migration
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, int64) (*github.Migration, error)); ok {
		return returnFunc(ctx, organization, migrationID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, int64) *github.Migration); ok {
		r0 = returnFunc(ctx, organization, migrationID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*github.Migration)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, int64) error); ok {
		r1 = returnFunc(ctx, organization, migrationID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockClient_GetMigrationStatus_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetMigrationStatus'
type MockClient_GetMigrationStatus_Call struct {
	*mock.Call
}

// GetMigrationStatus is a helper method to define mock.On call
//   - ctx context.Context
//   - organization string
//   - migrationID int64
func (_e *MockClient_Expecter) GetMigrationStatus(ctx interface{}, organization interface{}, migrationID interface{}) *MockClient_GetMigrationStatus_Call {
	return &MockClient_GetMigrationStatus_Call{Call: _e.mock.On("GetMigrationStatus", ctx, organization, migrationID)}
}

func (_c *MockClient_GetMigrationStatus_Call) Run(run func(ctx context.Context, organization string, migrationID int64)) *MockClient_GetMigrationStatus_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 int64
		if args[2] != nil {
			arg2 = args[2].(int64)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockClient_GetMigrationStatus_Call) Return(migration *github.Migration, err error) *MockClient_GetMigrationStatus_Call {
	_c.Call.Return(migration, err)
	return _c
}

func (_c *MockClient_GetMigrationStatus_Call) RunAndReturn(run func(ctx context.Context, organization string, migrationID int64) (*github.Migration, error)) *MockClient_GetMigrationStatus_Call {
	_c.Call.Return(run)
	return _c
}

// ListOrgRepos provides a mock function for the type MockClient
func (_mock *MockClient) ListOrgRepos(ctx context.Context, organization string, visibility string) ([]*github.Repository, error) {
	ret := _mock.Called(ctx, organization, visibility)

	if len(ret) == 0 {
		panic("no return value specified for ListOrgRepos")
	}

	var r0 []*github.Repository
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string) ([]*github.Repository, error)); ok {
		return returnFunc(ctx, organization, visibility)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string) []*github.Repository); ok {
		r0 = returnFunc(ctx, organization, visibility)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*github.Repository)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, string) error); ok {
		r1 = returnFunc(ctx, organization, visibility)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockClient_ListOrgRepos_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListOrgRepos'
type MockClient_ListOrgRepos_Call struct {
	*mock.Call
}

// ListOrgRepos is a helper method to define mock.On call
//   - ctx context.Context
//   - organization string
//   - visibility string
func (_e *MockClient_Expecter) ListOrgRepos(ctx interface{}, organization interface{}, visibility interface{}) *MockClient_ListOrgRepos_Call {
	return &MockClient_ListOrgRepos_Call{Call: _e.mock.On("ListOrgRepos", ctx, organization, visibility)}
}

func (_c *MockClient_ListOrgRepos_Call) Run(run func(ctx context.Context, organization string, visibility string)) *MockClient_ListOrgRepos_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockClient_ListOrgRepos_Call) Return(repositorys []*github.Repository, err error) *MockClient_ListOrgRepos_Call {
	_c.Call.Return(repositorys, err)
	return _c
}

func (_c *MockClient_ListOrgRepos_Call) RunAndReturn(run func(ctx context.Context, organization string, visibility string) ([]*github.Repository, error)) *MockClient_ListOrgRepos_Call {
	_c.Call.Return(run)
	return _c
}

// StartMigration provides a mock function for the type MockClient
func (_mock *MockClient) StartMigration(ctx context.Context, organization string, repoNames []string) (*github.Migration, error) {
	ret := _mock.Called(ctx, organization, repoNames)

	if len(ret) == 0 {
		panic("no return value specified for StartMigration")
	}

	var r0 *github.Migration
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, []string) (*github.Migration, error)); ok {
		return returnFunc(ctx, organization, repoNames)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, []string) *github.Migration); ok {
		r0 = returnFunc(ctx, organization, repoNames)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*github.Migration)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, []string) error); ok {
		r1 = returnFunc(ctx, organization, repoNames)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockClient_StartMigration_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'StartMigration'
type MockClient_StartMigration_Call struct {
	*mock.Call
}

// StartMigration is a helper method to define mock.On call
//   - ctx context.Context
//   - organization string
//   - repoNames []string
func (_e *MockClient_Expecter) StartMigration(ctx interface{}, organization interface{}, repoNames interface{}) *MockClient_StartMigration_Call {
	return &MockClient_StartMigration_Call{Call: _e.mock.On("StartMigration", ctx, organization, repoNames)}
}

func (_c *MockClient_StartMigration_Call) Run(run func(ctx context.Context, organization string, repoNames []string)) *MockClient_StartMigration_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 []string
		if args[2] != nil {
			arg2 = args[2].([]string)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockClient_StartMigration_Call) Return(migration *github.Migration, err error) *MockClient_StartMigration_Call {
	_c.Call.Return(migration, err)
	return _c
}

func (_c *MockClient_StartMigration_Call) RunAndReturn(run func(ctx context.Context, organization string, repoNames []string) (*github.Migration, error)) *MockClient_StartMigration_Call {
	_c.Call.Return(run)
	return _c
}
