// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"
	"io"

	mock "github.com/stretchr/testify/mock"
)

// NewMockBlobRepository creates a new instance of MockBlobRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockBlobRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockBlobRepository {
	mock := &MockBlobRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockBlobRepository is an autogenerated mock type for the BlobRepository type
type MockBlobRepository struct {
	mock.Mock
}

type MockBlobRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MockBlobRepository) EXPECT() *MockBlobRepository_Expecter {
	return &MockBlobRepository_Expecter{mock: &_m.Mock}
}

// Upload provides a mock function for the type MockBlobRepository
func (_mock *MockBlobRepository) Upload(ctx context.Context, blobName string, in io.Reader) (string, error) {
	ret := _mock.Called(ctx, blobName, in)

	if len(ret) == 0 {
		panic("no return value specified for Upload")
	}

	var r0 string
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, io.Reader) (string, error)); ok {
		return returnFunc(ctx, blobName, in)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, io.Reader) string); ok {
		r0 = returnFunc(ctx, blobName, in)
	} else {
		r0 = ret.Get(0).(string)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, io.Reader) error); ok {
		r1 = returnFunc(ctx, blobName, in)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockBlobRepository_Upload_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Upload'
type MockBlobRepository_Upload_Call struct {
	*mock.Call
}

// Upload is a helper method to define mock.On call
//   - ctx context.Context
//   - blobName string
//   - in io.Reader
func (_e *MockBlobRepository_Expecter) Upload(ctx interface{}, blobName interface{}, in interface{}) *MockBlobRepository_Upload_Call {
	return &MockBlobRepository_Upload_Call{Call: _e.mock.On("Upload", ctx, blobName, in)}
}

func (_c *MockBlobRepository_Upload_Call) Run(run func(ctx context.Context, blobName string, in io.Reader)) *MockBlobRepository_Upload_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 io.Reader
		if args[2] != nil {
			arg2 = args[2].(io.Reader)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockBlobRepository_Upload_Call) Return(s string, err error) *MockBlobRepository_Upload_Call {
	_c.Call.Return(s, err)
	return _c
}

func (_c *MockBlobRepository_Upload_Call) RunAndReturn(run func(ctx context.Context, blobName string, in io.Reader) (string, error)) *MockBlobRepository_Upload_Call {
	_c.Call.Return(run)
	return _c
}
